networks:
  app-network:
    driver: bridge

volumes:
  redis-data:

services:

  laravel-admin:
    build:
      context: ./laravel-admin
    container_name: laravel-admin
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./laravel-admin:/app
    environment:
      APP_ENV: local
      APP_KEY: ${ADMIN_APP_KEY}
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: influencer
      DB_USERNAME: root
      DB_PASSWORD: root
      REDIS_HOST: redis
      REDIS_PORT: 6379
      QUEUE_CONNECTION: rabbitmq
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT:-5671}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST}
      RABBITMQ_QUEUE: email.queue
    depends_on:
      - db
      - redis
    networks:
      - app-network

  emails:
    build:
      context: ./emails
    container_name: emails-service
    restart: unless-stopped
    volumes:
      - ./emails:/app
    environment:
      APP_ENV: local
      APP_KEY: ${EMAIL_APP_KEY}
      QUEUE_CONNECTION: rabbitmq
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT:-5671}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST}
      RABBITMQ_QUEUE: email.queue
      MAIL_MAILER: ${MAIL_MAILER:-mailpit}
      MAIL_HOST: ${MAIL_HOST:-mailpit}
      MAIL_PORT: ${MAIL_PORT:-1025}
      MAIL_USERNAME: ${MAIL_USERNAME:-null}
      MAIL_PASSWORD: ${MAIL_PASSWORD:-null}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS:-hello@example.com}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME:-MyApp}
    depends_on:
      - mailpit
    networks:
      - app-network

  react-admin:
    build:
      context: ./react-admin
      args:
        REACT_APP_API_URL: http://localhost:8000/api/admin
    container_name: react-admin
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - laravel-admin
    networks:
      - app-network

  react-influencer:
    build:
      context: ./react-influencer
      args:
        REACT_APP_API_URL: http://localhost:8000/api/influencer
        REACT_APP_CHECKOUT_URL: http://localhost:3002
    container_name: react-influencer
    restart: unless-stopped
    ports:
      - "3001:80"
    depends_on:
      - laravel-admin
    networks:
      - app-network

  next-checkout:
    build:
      context: ./next-checkout
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8000/api/checkout
        NEXT_PUBLIC_STRIPE_KEY: pk_test_51TgfwzCxnrjNjmoRhIJFaovmoNhNmwMxAlS36KTIUjocg3qrPb4TNfeR2GMvdnhX3HmORpOfQO4VHm09Lbg10L3300P2zuto0f
    container_name: next-checkout
    restart: unless-stopped
    ports:
      - "3002:3000"
    depends_on:
      - laravel-admin
    networks:
      - app-network

  db:
    image: mysql:9.7.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: influencer
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./.dbdata:/var/lib/mysql
    ports:
      - "33066:3306"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: admin-pma
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - app-network

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - app-network